### ISSUE TITLE
Background URL is static

### ISSUE THREAD

**Issue by danielyen** [nedaszilinskas/Odoo-CMS-Tabs-Building-Block#1]
Hello,

  I have used your Tabs Building Block module, and I would like to thank you for your work!  It has been helpful and useful.

  I seem to have bumped into an issue, and I would like to bounce it off with you to confirm it.

  I built a section of this module within my website on a development platform.  When I ported it over to the production platform, the background images' URL were found to be linking back to my development platform's URL.  It looks to be statically coded, and I had to manually edit all the URLs through the HTML editor.

  If this is what is happening, is it possible to modify the code so that the background images' URL contains only the context root, without host name or IP?

  Thank you for your time and effort.

**Comment by nedaszilinskas** [comment]
Hello danielyen,

If I understood you correctly it does not qualify as an issue since its normal behaviour of Odoo.
All content is saved into a template (including links), so when you move database you have exact same content (including links).

To avoid this you should use relative paths on your development database, so when you move it, it would point to same domain/IP or use some kind of tool to search and replace DB.

**Comment by danielyen** [comment]
Hello Nedas,

  I didn't have the same problem when I used Odoo's provided blocks within the website, hence I thought it could be an issue within your module.

  Thank you for responding back.  I will look into how I can implement relative paths within the database level.
