### ISSUE TITLE
Tabs don't show up

### ISSUE THREAD

**Issue by conerix** [nedaszilinskas/Odoo-CMS-Tabs-Building-Block#2]
I tried several enviroments on differen installations.. but no tabs show up
![bildschirmfoto vom 2015-10-12 23 58 50](https://cloud.githubusercontent.com/assets/15069568/10439869/39fdb65e-713d-11e5-8ce8-0719d697860d.png)
![bildschirmfoto vom 2015-10-12 23 59 38](https://cloud.githubusercontent.com/assets/15069568/10439880/52fb1732-713d-11e5-94b0-24cbe785ffdc.png)

**Comment by nedaszilinskas** [comment]
Hi conerix,

I think you are trying it on a custom theme? If so it does not work with custom themes due to an issue in website_less module preventing having tabs in snippet.

To temporary fix this (until odoo fixes it) you may need to edit website_less/static/src/js/website.snippets.editor.js file, lines 126 and 127.

<b>Current code:</b>
var categories = this.$snippet.find(".tab-pane.active")
.add(this.$snippet.find(".tab-pane:not(.active)"))

<b>Modified code:</b>
var categories = this.$snippet.find(".tab-pane.active:not(.oe_snippet_body .tab-pane)")
.add(this.$snippet.find(".tab-pane:not(.active):not(.oe_snippet_body .tab-pane)"))

Modified code wont allow odoo to hide tabs if those are in actual snippets.

**Comment by conerix** [comment]
yeah great.. it works.. thanx a lot.. 
you do a good job
